### ISSUE TITLE
Error with audio.h library

### ISSUE THREAD

**Issue by Marcelverhoeven** [techiesms/ESP32-ChatGPT-V2#1]
The fist part of this project works well!
But now I try to compile ESP32_Text_to_Speech.ino  and that fails. I have the board version 1.0.6
I work with Arduino IDE 2.2.1.
I do have installed the library from https://github.com/schreibfaul1/ESP32-audioI2S.git
But I get these errors:
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp: In constructor 'Audio::Audio(bool, uint8_t, uint8_t)':
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:206:18: error: 'struct i2s_config_t' has no member named 'mclk_multiple'
     m_i2s_config.mclk_multiple        = I2S_MCLK_MULTIPLE_128;
                  ^
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:206:41: error: 'I2S_MCLK_MULTIPLE_128' was not declared in this scope
     m_i2s_config.mclk_multiple        = I2S_MCLK_MULTIPLE_128;
                                         ^
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:212:65: error: 'I2S_COMM_FORMAT_STAND_MSB' was not declared in this scope
         m_i2s_config.communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_STAND_MSB); // vers >= 2.0.5
                                                                 ^
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:222:65: error: 'I2S_COMM_FORMAT_STAND_I2S' was not declared in this scope
         m_i2s_config.communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_STAND_I2S); // Arduino vers. > 2.0.0
                                                                 ^
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp: In member function 'const char* Audio::parsePlaylist_M3U8()':
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:2563:45: error: 'lltoa' was not declared in this scope
                     lltoa(xMedSeq, llasc, 10);
                                             ^
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp: In member function 'uint64_t Audio::m3u8_findMediaSeqInURL()':
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:2786:31: error: 'lltoa' was not declared in this scope
             lltoa(b, llasc, 10);
                               ^
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp: In member function 'bool Audio::setPinout(uint8_t, uint8_t, uint8_t, int8_t)':
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:4508:18: error: 'struct i2s_pin_config_t' has no member named 'mck_io_num'
     m_pin_config.mck_io_num = MCLK;
                  ^
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp: In member function 'void Audio::setI2SCommFMT_LSB(bool)':
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:4686:65: error: 'I2S_COMM_FORMAT_STAND_MSB' was not declared in this scope
         m_i2s_config.communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_STAND_MSB); // v >= 2.0.0
                                                                 ^
c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:4690:65: error: 'I2S_COMM_FORMAT_STAND_I2S' was not declared in this scope
         m_i2s_config.communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_STAND_I2S); // vers >= 2.0.0
                                                                 ^

exit status 1

Compilation error: exit status 1

==> Please help

**Comment by Marcelverhoeven** [comment]
I dit some more trial and error : The resolution is to install board version 2.0.14

**Comment by kaloprojects** [comment]
Awesome ... you made my day !!! :) .. i had same problem .. searched a whole day without idea .. then found your post :)
Thank you for this info, just tested .. now it works !
(i am using this board: ESP32 Dev (38 pins): https://www.az-delivery.de/en/products/esp32-developmentboard

Minor question (i did not test yet): can we use same 2.0.14 also for the left ESP (Speech to Text) .. or how to toggle in coding between both ESP32 ?

Thx again ! :)

**Comment by adityajain407** [comment]
> The fist part of this project works well! But now I try to compile ESP32_Text_to_Speech.ino and that fails. I have the board version 1.0.6 I work with Arduino IDE 2.2.1. I do have installed the library from https://github.com/schreibfaul1/ESP32-audioI2S.git But I get these errors: c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp: In constructor 'Audio::Audio(bool, uint8_t, uint8_t)': c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:206:18: error: 'struct i2s_config_t' has no member named 'mclk_multiple' m_i2s_config.mclk_multiple = I2S_MCLK_MULTIPLE_128; ^ c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:206:41: error: 'I2S_MCLK_MULTIPLE_128' was not declared in this scope m_i2s_config.mclk_multiple = I2S_MCLK_MULTIPLE_128; ^ c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:212:65: error: 'I2S_COMM_FORMAT_STAND_MSB' was not declared in this scope m_i2s_config.communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_STAND_MSB); // vers >= 2.0.5 ^ c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:222:65: error: 'I2S_COMM_FORMAT_STAND_I2S' was not declared in this scope m_i2s_config.communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_STAND_I2S); // Arduino vers. > 2.0.0 ^ c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp: In member function 'const char* Audio::parsePlaylist_M3U8()': c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:2563:45: error: 'lltoa' was not declared in this scope lltoa(xMedSeq, llasc, 10); ^ c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp: In member function 'uint64_t Audio::m3u8_findMediaSeqInURL()': c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:2786:31: error: 'lltoa' was not declared in this scope lltoa(b, llasc, 10); ^ c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp: In member function 'bool Audio::setPinout(uint8_t, uint8_t, uint8_t, int8_t)': c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:4508:18: error: 'struct i2s_pin_config_t' has no member named 'mck_io_num' m_pin_config.mck_io_num = MCLK; ^ c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp: In member function 'void Audio::setI2SCommFMT_LSB(bool)': c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:4686:65: error: 'I2S_COMM_FORMAT_STAND_MSB' was not declared in this scope m_i2s_config.communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_STAND_MSB); // v >= 2.0.0 ^ c:\Users\marce\Documents\Arduino\libraries\ESP32-audioI2S-master\src\Audio.cpp:4690:65: error: 'I2S_COMM_FORMAT_STAND_I2S' was not declared in this scope m_i2s_config.communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_STAND_I2S); // vers >= 2.0.0 ^
> 
> exit status 1
> 
> Compilation error: exit status 1
> 
> ==> Please help

you need to install Arduino ide 1.8.19 and download audio.h 2.3-2.6 to fix issue

**Comment by adityajain407** [comment]
you need to install Arduino ide 1.8.19 and download audio.h 2.3-2.6 to fix issue
